### ISSUE TITLE
Дублирование кода

### ISSUE THREAD

**Issue by asavochkin** [TMNova/Trainee_Chess#2]
https://github.com/TMNova/Trainee_Chess/blob/4244c4a5d25e0b10f4bb96eb93d3793807659606/src/ru/lanit/board/ChessBoard.java#L120

Дублируется код хода белых черных и проверки того, что не осталось доступных ходов

**Comment by TMNova** [comment]
Дублирование убрал, ходы черных и белых разделил на отдельные методы внутри класса.
Теперь выглядит вот так:
`public void playChess() {
        while (true) {
            stepWhiteFigures();
            showBoard(board);
            cloneChessBoard = cloneBoard(board);
            if (cantMove()) break;

            stepBlackFigures();
            showBoard(board);
            cloneChessBoard = cloneBoard(board);
            if (cantMove()) break;
        }
    }
 `
