### ISSUE TITLE
наименование 

### ISSUE THREAD

**Issue by asavochkin** [TMNova/Trainee_Chess#3]
https://github.com/TMNova/Trainee_Chess/blob/4244c4a5d25e0b10f4bb96eb93d3793807659606/src/ru/lanit/board/ChessBoard.java#L245

Чуть чуть неточно. я так понимаю суть в копировании доски?

**Comment by TMNova** [comment]
Да, все верно. Исправил.
`String[][] cloneBoard(String[][] board) {`
