### ISSUE TITLE
наименование полей и переменных (тут и везде по проекту!)

### ISSUE THREAD

**Issue by asavochkin** [TMNova/Trainee_Chess#6]
https://github.com/TMNova/Trainee_Chess/blob/4244c4a5d25e0b10f4bb96eb93d3793807659606/src/ru/lanit/figures/Pawn.java#L37

Названия типа a, pw, cc,bb,sd и т.п. - это жесть. код надо как будто "читать"

**Comment by TMNova** [comment]
Исправил.
