### ISSUE TITLE
отметка об объекте внутри доски

### ISSUE THREAD

**Issue by asavochkin** [TMNova/Trainee_Chess#8]
https://github.com/TMNova/Trainee_Chess/blob/4244c4a5d25e0b10f4bb96eb93d3793807659606/src/ru/lanit/figures/Pawn.java#L43

Логику я понял. Если ничего нет, то -, если пешка, то другой символ, если конь то третий и т.п.
Фиг с ним, что само решение ну так себе не очень изящное с точки зрения красоты, можно было сами объекте как то класть например, ну ладно, это пол беды, чувство прекрасного еще придет со врменем. 
Но тут есть косяк. вот эти константы-символы много раз дублируюсят в коде прямо в виде символов. Ничего не должно дублироваться (в идеале конечно), так как если ты в 1 месте решишь поменять - на 0, то потом надо будет искать по всему проекту, где надо заменить, и обязательно ошибешься пару раз. А если ты это сделаешь как то так, чтобы это контролировалось компилятором (например вынесешь именно в константу, или в метод какой), то тебе компилятор скажет в каких местах это используется.

**Comment by TMNova** [comment]
Заменил литералы - переменными типа с модификатором final
